name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    strategy:
      fail-fast: false
      matrix:
          ros_distro: [humble, iron, rolling]
    steps:
    - name: Build and run tests
      id: action-ros-ci
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        import-token: ${{ secrets.GITHUB_TOKEN }}
        target-ros2-distro: ${{ matrix.ros_distro }}
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\""
              ]
            }
          }
    - uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
