name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu }}-latest
    env:
      ROS_DISTRO: ${{ matrix.ros_distro }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: humble
            ubuntu: jammy
          - ros_distro: iron
            ubuntu: jammy
          - ros_distro: jazzy
            ubuntu: noble
          - ros_distro: rolling
            ubuntu: noble
    steps:
    - name: Build and run tests
      id: action-ros-ci
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        import-token: ${{ secrets.GITHUB_TOKEN }}
        target-ros2-distro: ${{ matrix.ros_distro }}
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\"",
                "-Dament_cmake_ROOT=\"/opt/ros/${{ matrix.ros_distro }}/share/\""
              ]
            }
          }
    - uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
